=== Questions & Answers

In this page you will find the common questions that may come to mind
when starting with QLC+.

Here you can either find the answer directly or find help to point you
in the right direction.

==== QLC+ cannot detect my USB device

QLC+ supports a wide variety of USB devices. First of all you
should check if the physical connection is OK. Usually a LED on your
device should indicate if it is powered up and working correctly.
If you are using Windows and your device is manufactured by Peperoni or
Velleman, please read the information on how to get them working on
these help pages. For licensing issues they both need an extra DLL file
to work. Please check link:peperonioutput.html[Peperoni output plugin]
or link:vellemanoutput.html[Velleman output plugin]
If you're using Linux, please check if your distribution detected the
device when plugged in. Basically, the "`+dmesg+`" command should tell
you something.


==== I've got several link:vcbutton.html[buttons] in my Virtual Console. I need a way to disable the currently active button when I enable another one. How do I do that?

Simply place your buttons inside a link:vcsoloframe.html[Solo
Frame]. It does exactly that.

==== I just upgraded my Mac to Mavericks (or later) and my USB DMX adapter doesn't transmit any data.

The problem is in an Apple driver called AppleUSBFTDI, which
takes control of every FTDI based device detected in the system.

There are a few ways to solve the problem, but basically the result is
the same: the Apple driver must be disabled.


Please check the dedicated page to understand how to
link:disable_apple_ftdi_driver.html[disable the Apple FTDI driver]

Otherwise, you can download the
https://www.dmxis.com/release/FtdiDriverControl.zip[ENTTEC FTDI Driver
Control tool] and try to enable/disable the Apple driver with it.


NOTE: this can compromise the behaviour of other USB devices, so do
it only if you know what you're doing!*

NOTE: every time Mac OS receives an update, you need to perform this
procedure again!*

NOTE: Most likely, when you disable/enable the Apple driver, you need
to reboot your Mac

==== Where is the QLC+ user folder located in my system?

The user folder is where user fixtures, input profiles, RGB scripts and
MIDI templates go.

It changes depending on your operating system:

*Linux*: it is a hidden folder in your user home directory:
$HOME/.qlcplus

*Windows*: it is a folder in your user (e.g. MyUser) directory:
C:\Users\MyUser\QLC+

*Mac OS*: it is located in your user "Library" directory:
$HOME/Library/Application\ Support/QLC+

You can reach any of these folders from a terminal with the 'cd'
command. For example:

....
cd $HOME/Library/Application\ Support/QLC+
....

Please keep in mind that fixures and input profiles found in the user
folder will have precedence over the same files in the QLC+ system
folder.

==== Where is the QLC+ system folder located in my system?

The system folder is where QLC+ resources (fixtures, input
profiles, RGB scripts, etc) are installed and it changes depending on
your operating system:

*Linux*: it's a fixed folder named /usr/share/qlcplus

*Windows*: it is the folder where you actually installed QLC+. By
default: C:\QLC+

*Mac OS*: it is a folder inside the QLC+ bundle (.app file). It is
possible to browse the QLC+.app bundle contents simply with Finder. Just
right click on the file and select "Show Package Contents".

Otherwise, the system folder can be reached with a terminal but it
depends on where you installed QLC+.

For example if you dragged QLC+ into Applications it will be:
/Applications/QLC+.app/Contents/Resources

==== QLC+ cannot play some videos on Windows

QLC+ relies on the Qt libraries which relies on the DirectShow
filters installed in the system.

Unfortunately the basic codecs supported by Windows are quite poor, so
you need to install some extra codecs package like K-Lite,
https://www.codecguide.com/download_kl.htm[available here].

==== I have a 4K display and everything in the QLC+ interface is extremely small

You need to add an option to the QLC+ command line to tell the Qt
libraries to autoscale the interface on a High DPI display. Examples:

....
Linux (from terminal): QT_AUTO_SCREEN_SCALE_FACTOR=1 qlcplus
....

....
Windows shortcut: C:\Windows\System32\cmd.exe /c "SET QT_AUTO_SCREEN_SCALE_FACTOR=1 && START /D ^"C:\QLC+^" qlcplus.exe"
....

....
Mac OS (from terminal): QT_AUTO_SCREEN_SCALE_FACTOR=1 QLC+.app\Contents\MacOS\qlcplus
....

In case, see the link:commandlineparameters.html[command line parameters
page] for further information.

